language: python
sudo: true

env:
  - distro: ubuntu1804

services:
  - docker

install:
  - wget https://releases.hashicorp.com/vagrant/2.0.4/vagrant_2.0.4_x86_64.deb
  - sudo apt install ./vagrant_2.0.4_x86_64.deb -y

cache:
  apt: true
  pip: true

addons:
  directories:
    - $HOME/.cache/pip
  apt:
    packages:
      - ansible
      # - vagrant

script:
  # - cd ./tests/
  - vagrant up --provider docker
