language: python
python: "2.7"
sudo: required

env:
  - distro: ubuntu1804

before_install:
  - sudo apt-get update -qq

services:
  - docker

install:
  # Install Ansible.
  - pip install ansible
  - apt-get install vagrant -y

script:
  - vagrant up --provider docker
  # 
  # container_id=$(mktemp)
  # - 'sudo docker run -d --name systemd --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t boxrick/bionic-docker-ansible > "${container_id}"'
