
env:
  - distro: ubuntu1804

services:
  - docker

sudo: false

cache:
    apt: true

addons:
  apt:
    packages:
      - ansible
      - vagrant

script:
  - cd ./tests/
  - vagrant up --provider docker
